# Generated by Django 5.2.7 on 2026-01-03 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_contact"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_unpublish_product", "Может отменять публикацию продукта"),
                    ("can_change_category", "Может изменять категорию продукта"),
                    ("can_moderate_product", "Может модерировать продукты"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(
                default=False,
                help_text="Продукт опубликован и виден всем пользователям",
                verbose_name="Опубликовано",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="moderated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата модерации"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="moderator_comment",
            field=models.TextField(
                blank=True,
                help_text="Комментарий модератора по продукту",
                null=True,
                verbose_name="Комментарий модератора",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Владелец продукта",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Черновик"),
                    ("moderation", "На модерации"),
                    ("published", "Опубликовано"),
                    ("rejected", "Отклонено"),
                ],
                default="draft",
                help_text="Статус продукта",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
